// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Services.DataContext;

#nullable disable

namespace Services.Migrations
{
    [DbContext(typeof(DataDemo))]
    [Migration("20230826072853_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Base.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab950de1-34ef-4e87-8111-fef59e38e467"),
                            Address = "Toshkent",
                            Email = "...",
                            Name = "Najot ta`lim",
                            Phone = "+998999999999"
                        },
                        new
                        {
                            Id = new Guid("5d76e748-011f-4cb6-bc8d-2423b06bb696"),
                            Address = "Toshkent",
                            Email = "...",
                            Name = "Kohinur",
                            Phone = "+998938853616"
                        });
                });

            modelBuilder.Entity("Base.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1af9ed4-7cb5-47af-963e-5ce381403e00"),
                            CompanyId = new Guid("5d76e748-011f-4cb6-bc8d-2423b06bb696"),
                            Email = "Sev@gmail.com",
                            FirstName = "Sevinch",
                            LastName = "Xayriddinova",
                            Phone = "+998939613663"
                        },
                        new
                        {
                            Id = new Guid("ffb9a741-99b1-4e9e-a44f-5d0b111dbc37"),
                            CompanyId = new Guid("ab950de1-34ef-4e87-8111-fef59e38e467"),
                            Email = "Sadaf@gmail.com",
                            FirstName = "Sadaf",
                            LastName = "Karimova",
                            Phone = "+998994027833"
                        });
                });

            modelBuilder.Entity("Base.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f30f95b-6ee6-4822-8fed-f53a4084383e"),
                            Name = "O`quv bo`limi"
                        },
                        new
                        {
                            Id = new Guid("eea4ff91-2222-4e5f-a0e0-d5a2348d9efe"),
                            Name = "Moliya bo`limi"
                        });
                });

            modelBuilder.Entity("Base.Models.StaffEmoloyee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffEmoloyees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9fa9ff6-fb96-488e-a8c1-9a59767a7706"),
                            EmployeeId = new Guid("b1af9ed4-7cb5-47af-963e-5ce381403e00"),
                            StaffId = new Guid("0f30f95b-6ee6-4822-8fed-f53a4084383e")
                        },
                        new
                        {
                            Id = new Guid("7838b104-32d2-47ba-b02b-3871cd03cafa"),
                            EmployeeId = new Guid("ffb9a741-99b1-4e9e-a44f-5d0b111dbc37"),
                            StaffId = new Guid("0f30f95b-6ee6-4822-8fed-f53a4084383e")
                        });
                });

            modelBuilder.Entity("Base.Models.Employee", b =>
                {
                    b.HasOne("Base.Models.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Base.Models.StaffEmoloyee", b =>
                {
                    b.HasOne("Base.Models.Employee", "Employee")
                        .WithMany("StaffEmoloyees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Base.Models.Staff", "Staff")
                        .WithMany("StaffEmoloyees")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Base.Models.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Base.Models.Employee", b =>
                {
                    b.Navigation("StaffEmoloyees");
                });

            modelBuilder.Entity("Base.Models.Staff", b =>
                {
                    b.Navigation("StaffEmoloyees");
                });
#pragma warning restore 612, 618
        }
    }
}
